version: '2'
services:
    jhipsterapplication-app:
        image: jhipsterapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterapplication-mysql:3306/jhipsterapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipsterapplication-mysql
